services:
  - type: web
    name: mini-erp
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL     # Neon ulanish manzili
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SELLER_PASSWORD
        sync: false
